# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.cache/wt [current_project]
set_property parent.project_path /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/powerups/strawberry.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/powerups/orange.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/powerups/key.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/food.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/powerups/energizer_powerup.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/powerups/apple.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_up_triangle.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_up_rectangle.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_scared_blue_triangle.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_scared_blue_rectangle.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_right_triangle.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_right_rectangle.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_left_triangle.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_left_rectangle.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_eyes_up.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_eyes_right.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_eyes_left.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_eyes_down.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_down_triangle.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/ghost/ghost_down_rectangle.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/new/divider_kim.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/new/divider.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_right_mouthopen.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_right_mouth1.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_right_mouth2.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_right_mouth3.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_left_mouthopen.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_up_mouth2.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_up_mouth3.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_down_mouth2.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_up_mouthopen.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_down_mouth1.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying11.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_up_mouth1.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_down_mouth3.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying10.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_left_mouth1.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_left_mouth3.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_left_mouth2.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying8.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying9.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_mouthclosed.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_down_mouthopen.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying4.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying5.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying6.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying7.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying1.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying2.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman_dying3.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/powerups/cherry.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/new/movement.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/new/pacman_life.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/new/display_food.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_p.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_v.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_u.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_t.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_s.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_r.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_o.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_n.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_m.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_l.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_i.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_g.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_e.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_d.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_c.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_b.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman_modules/characters/letter_a.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/new/box.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/new/location_blocked.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/new/grid.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/new/controler_clk.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/new/timer.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/new/collision.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/pacman/pacman.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/gameplay_fsm.srcs/ghost.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/sources/enemy_ai.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/new/game_menu.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/new/display_lives.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/sources/debounce.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/sources/display_8hex.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/new/level_builder.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/new/nes_controler.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/new/game_fsm.v
  /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/sources_1/imports/sources/labkit_lab4.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/constrs_1/imports/sources/Nexys4DDR_Master_lab4.xdc
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/r/d/rdevlin/6.111work/Final_project/gameplay_fsm/gameplay_fsm.srcs/constrs_1/imports/sources/Nexys4DDR_Master_lab4.xdc]


synth_design -top labkit -part xc7a100tcsg324-3


write_checkpoint -force -noxdef labkit.dcp

catch { report_utilization -file labkit_utilization_synth.rpt -pb labkit_utilization_synth.pb }
